import './style.css';
import {createScene} from './scene.js';
const $=id=>document.getElementById(id), screen=$('emulator-screen');
let machine,engine=null,rom=null,busy=false,on=false,paused=false,muted=false,view='orbit',noticeTimer,dbPromise,operation=0;
const held=new Set(),buttonPointers=new Map();
const BASE=import.meta.env.BASE_URL;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('toast').hidden=true,6500);}
function status(message){$('status').textContent=message;}
function blank(){const c=screen.getContext('2d');c.fillStyle='#1c282b';c.fillRect(0,0,240,160);c.fillStyle='#82968c';c.fillRect(103,51,35,23);c.fillRect(108,47,24,5);c.fillStyle='#273c38';c.fillRect(109,56,13,4);c.fillRect(114,51,4,14);c.fillRect(128,56,4,4);c.font='7px monospace';c.textAlign='center';c.fillStyle='#6e8780';c.fillText('INSERT CARTRIDGE',120,103);c.fillText('AND MAKE A LITTLE TIME.',120,116);}
blank();
function database(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('pocket-gba-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('saves');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('浏览器存储不可用，请导出备份'));});return dbPromise;}
async function store(key,value){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('saves','readwrite');tx.objectStore('saves').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(new Error('存档写入失败，请检查浏览器存储空间'));tx.onabort=()=>reject(new Error('存档写入已中止'));});}
async function read(key){const db=await database();return new Promise((resolve,reject)=>{const r=db.transaction('saves').objectStore('saves').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('无法读取存档'));});}
function sync(){const p=$('primary');p.disabled=busy;p.replaceChildren(document.createTextNode(busy?'正在加载真实游戏…':on?'更换游戏卡带':rom?'插入并开机':'选择游戏卡带'));const arrow=document.createElement('span');arrow.textContent='→';p.append(arrow);$('session-controls').hidden=!on;for(const id of ['pause','eject','mute','save','restore','export','import'])$(id).disabled=busy||!engine;$('demo').disabled=busy;$('pause').textContent=paused?'继续':'暂停';$('mute').textContent=muted?'开启声音':'静音';document.body.classList.toggle('playing',on&&view==='play');for(const type of ['play','orbit','back','card'])$('view-'+type).setAttribute('aria-pressed',String(type===view));}
function key(code,pressed){if(pressed&&(!on||paused||busy||view!=='play'))return;if(pressed)held.add(code);else held.delete(code);window.dispatchEvent(new KeyboardEvent(pressed?'keydown':'keyup',{code,key:code==='Enter'?'Enter':'',bubbles:true,cancelable:true}));machine?.press(code,pressed);}
function releaseAll(){for(const code of [...held])key(code,false);for(const code of ['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyX','KeyZ','KeyA','KeyS','Enter','ShiftRight']){window.dispatchEvent(new KeyboardEvent('keyup',{code,bubbles:true}));machine?.press(code,false);}buttonPointers.clear();document.querySelectorAll('[data-key]').forEach(b=>b.classList.remove('active'));}
async function save(notify=false){if(!engine||!rom)return;const bytes=await engine.saveState();await store(rom.hash,{version:1,hash:rom.hash,name:rom.name,core:'mgba-wasm-0.1.1',bytes,at:Date.now()});$('save-note').textContent='进度已保存到当前浏览器 · '+new Date().toLocaleTimeString();if(notify)toast('进度已保存');}
async function pauseGame(persist=true){if(!engine)return;releaseAll();engine.pause();paused=true;status('游戏已暂停');sync();if(persist)await save(false);}
function resume(){if(!engine)return;engine.resume();paused=false;status('游戏运行中');sync();}
async function changeView(next){if(busy)return;if(next!=='play'&&on&&!paused)await pauseGame();view=next;machine.setView(next);$('hint').textContent=next==='play'?'键盘 / 触屏 / 标准手柄 · 可以真正游玩':next==='card'?'拖动旋转卡带 · 返回游玩视角可继续游戏':'拖动旋转 · 滚轮缩放 · 卡带可以向下插入';if(next==='play'&&on)resume();sync();}
async function stop(){if(!engine)return;await pauseGame(true);engine.destroy();engine=null;on=false;paused=false;operation++;machine.setPower(false);machine.setInserted(false);blank();status('卡带已退出，进度已保存');$('fps').textContent='';await changeView('orbit');sync();}
async function select(bytes,name){if(busy)return;if(bytes.byteLength<192||bytes.byteLength>33554432)throw new Error('请选择有效的 .gba 文件（192 字节至 32 MB）');if(bytes[0xb2]!==0x96)throw new Error('这个文件不是标准 GBA 卡带，请确认不是压缩包或网页文件');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(engine)await stop();rom={bytes,name,hash};machine.setInserted(false);machine.setCard(name.replace(/\.gba$/i,''));$('romname').textContent=name;status('卡带已就绪 · 点击插入并开机');sync();}
async function boot(){if(busy||on)return;if(!rom){$('romfile').click();return;}busy=true;releaseAll();sync();status('正在装载 mGBA 核心…');machine.setInserted(true);machine.setView('play');view='play';const token=++operation;let timer;try{const init=(async()=>{const sdk=await import(/* @vite-ignore */BASE+'vendor/mgba.sdk.js');const e=await sdk.load({canvasEl:screen,assets:{rom:rom.bytes},options:{system:'gba',renderFilter:'pixelated',escMenu:false,volume:muted?0:1},persist:'opfs',storageNamespace:'pocket-'+rom.hash,onEvent:event=>{if(event.type==='frame'&&on)$('fps').textContent=Math.round(event.fps)+' FPS';}});if(token!==operation){e.destroy();throw new Error('加载已取消');}return e;})();const e=await Promise.race([init,new Promise((_,reject)=>timer=setTimeout(()=>{operation++;reject(new Error('游戏核心加载超时。请检查网络后重试'));},30000))]);clearTimeout(timer);engine=e;engine.setInput({'p1.select':'ShiftRight'});engine.start();on=true;paused=false;machine.setPower(true);try{const cached=await read(rom.hash);if(cached?.core==='mgba-wasm-0.1.1')await engine.loadState(new Uint8Array(cached.bytes));}catch(err){toast('游戏已启动，但上次进度未恢复：'+err.message);}status('游戏运行中');$('hint').textContent='键盘 / 触屏 / 标准手柄 · 可以真正游玩';}catch(err){clearTimeout(timer);engine?.destroy();engine=null;on=false;machine.setPower(false);machine.setInserted(false);blank();status('启动失败，可重试');toast(err.message||'模拟器启动失败');}finally{busy=false;sync();}}
function safely(fn){return(...args)=>Promise.resolve().then(()=>fn(...args)).catch(err=>{console.warn(err);toast(err.message||'操作未完成');sync();});}
try{machine=createScene($('stage'),screen,{key,insert:safely(boot),power:safely(()=>on?stop():boot())});$('scene-loading').remove();}catch(err){$('scene-loading').textContent='当前浏览器无法开启 3D。请使用支持 WebGL 的浏览器。';status('WebGL 初始化失败');$('primary').disabled=true;throw err;}
$('primary').onclick=safely(()=>on||!rom?$('romfile').click():boot());$('romfile').onchange=safely(async()=>{const f=$('romfile').files[0];$('romfile').value='';if(!f)return;if(!/\.gba$/i.test(f.name))throw new Error('请选择 .gba 文件');await select(new Uint8Array(await f.arrayBuffer()),f.name);});
$('demo').onclick=safely(async()=>{const r=await fetch(BASE+'pocket-test.gba');if(!r.ok)throw new Error('测试卡加载失败');await select(new Uint8Array(await r.arrayBuffer()),'Pocket Field Test.gba');});
for(const type of ['play','orbit','back','card'])$('view-'+type).onclick=safely(()=>changeView(type));
$('pause').onclick=safely(()=>paused?changeView('play'):pauseGame());$('eject').onclick=safely(stop);$('save').onclick=safely(()=>save(true));
$('restore').onclick=safely(async()=>{const cached=await read(rom.hash);if(!cached)throw new Error('这张卡带还没有保存过进度');releaseAll();await engine.loadState(new Uint8Array(cached.bytes));toast('已恢复保存的进度');});
$('mute').onclick=()=>{muted=!muted;engine?.config.write('volume',muted?0:1);sync();};
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
$('export').onclick=safely(async()=>{const bytes=await engine.saveState();let b='';for(let i=0;i<bytes.length;i+=8192)b+=String.fromCharCode(...bytes.subarray(i,i+8192));download(new Blob([JSON.stringify({format:'pocket-save',version:1,core:'mgba-wasm-0.1.1',hash:rom.hash,name:rom.name,data:btoa(b)})],{type:'application/json'}),rom.name.replace(/\.gba$/i,'')+'.pocket');toast('已生成存档文件');});
$('import').onclick=()=>$('savefile').click();$('savefile').onchange=safely(async()=>{const f=$('savefile').files[0];$('savefile').value='';if(!f)return;if(f.size>2000000)throw new Error('存档文件过大');const data=JSON.parse(await f.text());if(data.format!=='pocket-save'||data.version!==1||data.core!=='mgba-wasm-0.1.1'||data.hash!==rom.hash||typeof data.data!=='string')throw new Error('这份存档不属于当前卡带或核心版本');releaseAll();const bytes=Uint8Array.from(atob(data.data),c=>c.charCodeAt(0));await engine.loadState(bytes);await save(false);toast('存档已导入并保存');});
$('help').onclick=safely(async()=>{if(on&&!paused)await pauseGame();$('help-dialog').showModal();});
for(const b of document.querySelectorAll('[data-color]'))b.onclick=()=>{machine.setColor(b.dataset.color);document.querySelectorAll('.swatch').forEach(s=>s.classList.toggle('selected',s===b));$('colorname').textContent=b.getAttribute('aria-label');};
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();if(!on||paused||busy)return;b.setPointerCapture(e.pointerId);buttonPointers.set(e.pointerId,b.dataset.key);b.classList.add('active');key(b.dataset.key,true);});const up=e=>{const code=buttonPointers.get(e.pointerId);buttonPointers.delete(e.pointerId);if(code&&![...buttonPointers.values()].includes(code)){key(code,false);b.classList.remove('active');}};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up);}
const mapped=new Set(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyX','KeyZ','KeyA','KeyS','Enter','ShiftRight','ShiftLeft']);
window.addEventListener('keydown',e=>{if(!e.isTrusted)return;const code=e.code==='ShiftLeft'?'ShiftRight':e.code;if(!mapped.has(e.code))return;if($('help-dialog').open||!on||paused||view!=='play'){if(on){e.stopImmediatePropagation();e.preventDefault();}return;}e.preventDefault();held.add(code);machine.press(code,true);if(e.code==='ShiftLeft')key('ShiftRight',true);},true);
window.addEventListener('keyup',e=>{if(!e.isTrusted)return;const code=e.code==='ShiftLeft'?'ShiftRight':e.code;held.delete(code);machine.press(code,false);if(e.code==='ShiftLeft')key('ShiftRight',false);},true);
window.addEventListener('blur',()=>{releaseAll();if(on&&!paused)safely(()=>pauseGame())();});document.addEventListener('visibilitychange',()=>{if(document.hidden){releaseAll();if(on&&!paused)safely(()=>pauseGame())();}});
setInterval(()=>{if(on&&!busy)save(false).catch(()=>{$('save-note').textContent='自动保存失败，请导出存档备份。';});},15000);
window.addEventListener('pagehide',()=>{releaseAll();engine?.pause();});
window.__pocket={get state(){return{on,paused,busy,view,rom:rom?.name};},get screen(){return screen;}};
sync();
