import {chromium,webkit} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const BASE=process.env.TEST_URL||'http://127.0.0.1:4173/chaogeek-publisher/pocket-gba/';
await mkdir('qa',{recursive:true});
const report={base:BASE,checks:[],errors:[]};
function ok(text){report.checks.push(text);console.log('PASS',text);}
async function heroX(page){return page.evaluate(()=>{const c=document.getElementById('emulator-screen');const d=c.getContext('2d').getImageData(0,0,240,160).data;let n=0,s=0;for(let y=30;y<135;y++)for(let x=0;x<240;x++){let i=(y*240+x)*4;if(d[i]>240&&d[i+1]<50&&d[i+2]>140&&d[i+2]<185){n++;s+=x;}}return n?s/n:null;});}
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});
const ctx=await browser.newContext({viewport:{width:1440,height:960}});const page=await ctx.newPage();page.on('pageerror',e=>report.errors.push(e.message));
try{
 await page.goto(BASE,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__pocket);await page.waitForTimeout(900);assert.equal(await page.locator('#stage canvas').count(),1);await page.screenshot({path:'qa/desktop.png',fullPage:true});ok('desktop 1440x960 renders real WebGL scene');
 await page.locator('#view-back').click();await page.waitForTimeout(700);await page.screenshot({path:'qa/back.png'});await page.locator('#view-card').click();await page.waitForTimeout(500);await page.locator('#view-orbit').click();ok('back and independent cartridge inspection work');
 await page.locator('#demo').click();await page.waitForFunction(()=>window.__pocket.state.rom);await page.locator('#primary').click();await page.waitForFunction(()=>window.__pocket.state.on,{},{timeout:60000});await page.waitForTimeout(1800);assert.equal(await page.locator('#emulator-screen').evaluate(c=>c.width),240);const x0=await heroX(page);assert.notEqual(x0,null,'real GBA demo must render its distinctive player');ok('native ARM GBA ROM runs in mGBA WASM');
 await page.keyboard.down('ArrowRight');await page.waitForTimeout(450);await page.keyboard.up('ArrowRight');await page.waitForTimeout(150);const x1=await heroX(page);assert(x1>x0+8,`keyboard movement ${x0} -> ${x1}`);ok('keyboard moves character in emulated framebuffer');
 await page.locator('#save').click();await page.waitForTimeout(500);const savedX=await heroX(page);await page.keyboard.down('ArrowRight');await page.waitForTimeout(400);await page.keyboard.up('ArrowRight');await page.locator('#restore').click();await page.waitForTimeout(600);assert(Math.abs(await heroX(page)-savedX)<3);ok('save and restore recover actual emulator state');
 await page.screenshot({path:'qa/gameplay.png',fullPage:true});await page.locator('#view-orbit').click();await page.waitForFunction(()=>window.__pocket.state.paused);await page.locator('#view-play').click();await page.waitForFunction(()=>!window.__pocket.state.paused);ok('inspection pauses; play view resumes same emulator');
 await page.locator('#eject').click();await page.waitForFunction(()=>!window.__pocket.state.on);await page.locator('#primary').click();await page.waitForFunction(()=>window.__pocket.state.on,{},{timeout:60000});await page.waitForTimeout(1000);assert(Math.abs(await heroX(page)-savedX)<3);ok('eject, reinsert and restore persisted state');
 const downloadP=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadP;assert(download.suggestedFilename().endsWith('.pocket'));ok('portable hash-bound save export');
 await page.locator('#romfile').setInputFiles({name:'bad.gba',mimeType:'application/octet-stream',buffer:Buffer.alloc(256)});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.__pocket.state.on),true);ok('invalid ROM rejected without destroying running game');
 await page.locator('#mute').click();await page.locator('#pause').click();await page.waitForFunction(()=>window.__pocket.state.paused);ok('mute and pause controls');
 assert.equal(report.errors.length,0,report.errors.join('\n'));
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});const mp=await mobile.newPage();await mp.goto(BASE,{waitUntil:'networkidle'});await mp.waitForFunction(()=>window.__pocket);await mp.waitForTimeout(700);assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mp.screenshot({path:'qa/mobile.png',fullPage:true});ok('mobile 390x844 has no horizontal overflow');
 await mp.locator('#demo').tap();await mp.waitForFunction(()=>window.__pocket.state.rom);await mp.locator('#primary').tap();await mp.waitForFunction(()=>window.__pocket.state.on,{},{timeout:60000});await mp.waitForTimeout(1000);assert(await mp.locator('#touchpad').isVisible());const mx=await heroX(mp);await mp.locator('[data-key="ArrowRight"]').dispatchEvent('pointerdown',{pointerId:7,pointerType:'touch',clientX:100,clientY:100});await mp.waitForTimeout(450);await mp.locator('[data-key="ArrowRight"]').dispatchEvent('pointerup',{pointerId:7,pointerType:'touch'});await mp.waitForTimeout(100);assert(await heroX(mp)>mx+8);await mp.screenshot({path:'qa/mobile-gameplay.png',fullPage:true});ok('mobile touch controls move real emulated character');await mobile.close();
}catch(e){report.errors.push(e.stack);await page.screenshot({path:'qa/failure.png',fullPage:true}).catch(()=>{});throw e;}finally{await writeFile('qa/report.json',JSON.stringify(report,null,2));await browser.close();}
